source "https://supermarket.getchef.com"

cookbook 'python'
cookbook 'chef-client'
cookbook 'apt', '>= 2.9.2'
cookbook 'mysql', '~> 8.0'
cookbook 'database', ">= 4.0.6"
cookbook 'hostsfile'
cookbook 'haproxy'
cookbook 'memcached'
cookbook 'logrotate'
# sysctl 0.4.0에는 sysctl 설정시 ruby_block[save-sysctl-params] notify하는데, 이게 선언이 안된 문제가 있음
cookbook 'sysctl', '~> 0.3.5'
cookbook 'omnibus_updater'
cookbook 'ohai'
cookbook 'apache2', '~> 3.1.0'
cookbook 'freebsd', '~> 0.1.9'
cookbook 'sysfs', '~> 0.0.2'
cookbook 'mongodb3', '~>3.0.0'
cookbook 'rabbitmq', '~> 4.5.1'
cookbook 'swift', path: 'cookbooks/swift'
cookbook 'kakao', path: 'cookbooks/kakao'
cookbook 'base', path: 'cookbooks/base'
cookbook 'openstack', path: 'cookbooks/openstack'
cookbook 'neutron', path: 'cookbooks/neutron'
cookbook 'keystone', path: 'cookbooks/keystone'
cookbook 'nova', path: 'cookbooks/nova'
cookbook 'horizon', path: 'cookbooks/horizon'
cookbook 'heat', path: 'cookbooks/heat'
cookbook 'glance', path: 'cookbooks/glance'
cookbook 'cinder', path: 'cookbooks/cinder'
cookbook 'ceilometer', path: 'cookbooks/ceilometer'
cookbook 'trove', path: 'cookbooks/trove'
cookbook 'sahara', path: 'cookbooks/sahara'
cookbook 'rsyslog'

## new systems
cookbook 'logstash','~> 0.9.2'
cookbook 'curl'
cookbook 'java'
cookbook 'kibana'
cookbook 'elasticsearch'
cookbook 'chef_handler'
