name             'openstack'
maintainer       'ccc'
maintainer_email 'ccc@kakaocorp.com'
license          'All rights reserved'
description      'Installs/Configures openstack'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.10.21'
supports 'ubuntu', '>= 12.04'

depends 'base'
depends 'apt'
depends 'ceph'
depends 'mysql2_chef_gem'
depends 'database'
depends 'rabbitmq'
depends 'kakao'
depends 'haproxy'
depends 'logrotate'
depends 'omnibus_updater'
depends 'python'
depends 'memcached'
