name             'nova'
maintainer       'ccc'
maintainer_email 'ccc@kakaocorp.com'
license          'All rights reserved'
description      'Installs/Configures nova'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.10.21'
supports 'ubuntu', '>= 12.04'

depends 'base'
depends 'openstack'
depends 'keystone'
depends 'glance'
depends 'cinder'
depends 'neutron'
depends 'ceilometer'
depends 'ceph'
depends 'logrotate'
depends 'sysctl'
depends 'sysfs'
