# generated by "figlet Welcome! ccc~"
return unless check_environment_production

package 'figlet'

banner = `which figlet > /dev/null && figlet -f big Welcome! ccc~ #{node.chef_environment}`
file '/etc/motd.tail' do
  content banner
end

cookbook_file '/etc/update-motd.d/99-footer' do
  source '99-footer'
  mode 00755
  notifies :run, "execute[update banner]"
end

execute 'update banner' do
  command 'run-parts /etc/update-motd.d/'
  action :nothing
end
